### ISSUE TITLE
Automatically setup tmux sessions off the root user for fast debugging

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/tripleo-quickstart-scalelab#73]
Establish tmux sessions off the root user to work with the Undercloud for debugging Overcloud deployment as well as post Overcloud deployment for faster manipulation of a subset of the overcloud nodes.

**Comment by akrzos** [comment]
#76 fixed this for undercloud debugging

**Comment by mbruzek** [comment]
I think this is done. Closing.
