### ISSUE TITLE
Profiles vs vars and consistent vars management

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/tripleo-quickstart-scalelab#80]
To make the repo easier to use, we should settle on a consistent passing of vars.  Right now vars are passed into a "profile" (vars file under directory profile) as well as which "profile" to use via Jenkins parameters.  Both staging and "production" use different profile files.  

I think we should have a single profile file (Lets just call this a vars file to be more consistent with Ansible practices) that consumes the Jenkins environment vars into Ansible vars.  Then whether using staging or production, you swap out the vars you are passing into Jenkins rather than both vars in Jenkins and potential vars in a "profile" vars file in the repo.  This will likely cause us to edit the Jenkins job but ultimately I think it will be easier to use/maintain.

Thoughts @chaitanyaenr @jmencak @mbruzek

**Comment by mbruzek** [comment]
Yes this sounds reasonable and I do want to make things easier. In my opinion we should expose the least amount of variables possible to reduce the chances of mistakes. 

A lot of effort has been put into carefully selecting the parameters on the Jenkins jobs to make sure sensitive data is not stored in the public repository. The solution using "variable files" going forward needs to make sure we are not checking in keys, passwords, internal addresses/hostnames, or other sensitive data to public repositories in clear text.

Technically we can use Ansible vault files but those need a password too and add complexity to the solution. As long as we do not put sensitive data in clear text in the repositories I am +1 to consolidating the variables.

**Comment by chaitanyaenr** [comment]
+1 on maintaining a single vars file. Like @akrzos mentioned, we need to have same set of vars for both staging, production. This way we need not maintain two different property files and groovy scripts for staging and production.

**Comment by akrzos** [comment]
We now have vars files for managing vars and both staging and production run through the same vars files.  Vars files are populated from Jenkins parameters via Ansible look-ups.  Thanks everyone for the feedback and help on streamlining this.  I have found it less difficult to explain the origin of configuration/templates etc with the setup so I will close this issue now.
